#!/usr/bin/env bash
# Regenerates NOTICE.md by listing all direct + transitive deps in both
# workspaces with their license. Commit the resulting NOTICE.md alongside
# code changes so it stays in sync.

set -euo pipefail

OUTPUT="${1:-NOTICE.md}"

generate_section() {
  local workspace="$1"
  echo "## $workspace dependencies"
  echo ""
  echo "| Package | Version | License |"
  echo "|---------|---------|---------|"
  (cd "$workspace" && npx --yes license-checker --json --production --excludePrivatePackages) \
    | node -e "
      const data = JSON.parse(require('fs').readFileSync(0,'utf8'));
      const rows = Object.entries(data)
        .map(([k,v]) => {
          const m = k.match(/^(.+)@([^@]+)$/);
          return { name: m[1], version: m[2], license: v.licenses };
        })
        .sort((a,b) => a.name.localeCompare(b.name));
      for (const r of rows) {
        const lic = Array.isArray(r.license) ? r.license.join(' OR ') : (r.license || 'UNKNOWN');
        process.stdout.write(\`| \${r.name} | \${r.version} | \${lic} |\n\`);
      }
    "
  echo ""
}

{
  echo "# NOTICE"
  echo ""
  echo "This file lists third-party dependencies bundled or referenced by Zugzug."
  echo "Auto-generated by \`scripts/generate-notice.sh\`. Do not edit by hand."
  echo ""
  echo "Generated: $(date -u +'%Y-%m-%d')"
  echo ""
  generate_section "server"
  generate_section "app"
} > "$OUTPUT"

echo "Wrote $OUTPUT"
